### ISSUE TITLE
UI For Interacting with Items

### ISSUE THREAD

**Issue by IsaiahMcLain** [CS328UnreliableNarrator/UnrealiableNarrator#12]
## Deliverables:
1. Have a small grey dot appear in the center of the players screen on first person view to show that an item is interactable. 
2. For this iteration, just make whatever object you want interactable just so we can test the UI and make sure it works, don't worry about what the object actually does

## Tips: 
1. Here's a unity tutorial for an idea of what our UI can look like, I like the idea of a hand when hovering over an interactable otherwise center crosshair is white dot: https://www.youtube.com/watch?v=lZThP8KG1W0
2. Action Map

**Comment by Stehfyn** [comment]
9caef7e
