### ISSUE TITLE
Add sound effects

### ISSUE THREAD

**Issue by IsaiahMcLain** [CS328UnreliableNarrator/UnrealiableNarrator#31]
## Deliverables:
1. Create audio listeners on prefabs and components that will need audio interactions
2. Create code that will enable audio to fire on whatever action is deemed necessary.
3. Add audio to those interactions

## Tips:
1. Don't worry about step 3 that will be my part, step 1 I'll have a list below of items that will need audio listeners and the overall idea.
2. https://www.youtube.com/watch?v=6OT43pvUyfY Here's a Brackey's tutorial about implementing audio

## List: 
1. Need audio listeners for door so I can have a sound for door opening and closing 
2. Need audio listener on computer prefabs so when interacted with they'll make a noise
3. Need audio listener on 9 pin puzzle activation and when user connects one node to another, will need a final listener for when user completes that puzzle
4. Need audio listener for when player solves email  puzzle to unlock maintenance door.
5. Need audio listener for when player interacts with wire box
6. Need audio listener for when player connects wires in wire puzzle and listener for when player completes puzzle

**Comment by Stehfyn** [comment]
115685b
28a4fc5

Email Puzzle Win is yet to be implemented as from my end the puzzle is unfinished? Also there's no background music or player walking sound. I will implement the hooks for those as well hopefully later in the day. Leaving this open until that's complete.
