### ISSUE TITLE
Door Tween

### ISSUE THREAD

**Issue by IsaiahMcLain** [CS328UnreliableNarrator/UnrealiableNarrator#35]
## Deliverables:
1. Tween animation for door to open and close when interacted with

##Tips: 
1. Look into ITween library: https://assetstore.unity.com/packages/tools/animation/itween-84
2. http://www.pixelplacement.com/itween/index.php

**Comment by Stehfyn** [comment]
Initial: 48eaa1e
Final: 0158475
